// GENERATED by `npm run db:pull` (drizzle-kit pull +
// scripts/patch-pulled-schema.mjs). Table ORDER in this file is not
// stable across pulls — diff it by content, not by line number.
import { pgTable, pgSchema, index, uniqueIndex, foreignKey, check, bigint, timestamp, text, boolean, inet, smallint, unique, char, varchar, numeric, integer, jsonb, time, primaryKey, date } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
import { citext, gstin, ltree, mobileIn, notifChannelArray, panNo, pincodeIn, roleKeyArray, vehicleReg } from "./types"

export const wms = pgSchema("wms");
export const accessScopeInWms = wms.enum("access_scope", ['NONE', 'OWN', 'WAREHOUSE', 'ALL'])
export const auditOperationInWms = wms.enum("audit_operation", ['INSERT', 'UPDATE', 'DELETE', 'RESTORE', 'LOGIN', 'LOGOUT', 'DENY', 'EXPORT', 'APPROVE', 'REJECT'])
export const auditResultInWms = wms.enum("audit_result", ['SUCCESS', 'DENIED', 'FAILED'])
export const creationScopeInWms = wms.enum("creation_scope", ['ANY', 'SAME_WAREHOUSE', 'SAME_IMPORTER', 'SELF_REGISTER'])
export const deliveryStatusInWms = wms.enum("delivery_status", ['PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'SUPPRESSED', 'EXPIRED'])
export const notifAudienceInWms = wms.enum("notif_audience", ['ACTOR', 'SUBJECT', 'PARENT', 'ANCESTORS', 'ALL_SUPER_ADMINS', 'ROLE', 'WAREHOUSE_ROLE', 'IMPORTER_ROLE', 'EXPLICIT'])
export const notifChannelInWms = wms.enum("notif_channel", ['IN_APP', 'EMAIL', 'SMS', 'PUSH', 'WHATSAPP'])
export const recordStatusInWms = wms.enum("record_status", ['DRAFT', 'PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED', 'REJECTED'])
export const roleDomainInWms = wms.enum("role_domain", ['PLATFORM', 'WAREHOUSE', 'IMPORTER'])
export const roleKeyInWms = wms.enum("role_key", ['SUPER_ADMIN', 'WAREHOUSE_ADMIN', 'TRANSPORTER_MANAGER', 'INWARD_MANAGER', 'STORAGE_MANAGER', 'PACKAGE_MANAGER', 'DISPATCH_MANAGER', 'IMPORTER', 'SALES_AGENT'])

export const auditLogIdSeqInWms = wms.sequence("audit_log_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const usersInWms = wms.table("users", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.users_id_seq", startWith: 1, increment: 1 }),
	email: citext("email").notNull(),
	emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true, mode: 'string' }),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	mobile: mobileIn("mobile").notNull(),
	mobileVerifiedAt: timestamp("mobile_verified_at", { withTimezone: true, mode: 'string' }),
	passwordHash: text("password_hash"),
	passwordChangedAt: timestamp("password_changed_at", { withTimezone: true, mode: 'string' }),
	photoUrl: text("photo_url"),
	locale: text().default('en').notNull(),
	timezone: text().default('Asia/Kolkata').notNull(),
	defaultRole: roleKeyInWms("default_role"),
	status: recordStatusInWms().default('ACTIVE').notNull(),
	mustChangePassword: boolean("must_change_password").default(false).notNull(),
	lastLoginAt: timestamp("last_login_at", { withTimezone: true, mode: 'string' }),
	lastLoginIp: inet("last_login_ip"),
	failedLoginCount: smallint("failed_login_count").default(0).notNull(),
	lockedUntil: timestamp("locked_until", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	path: ltree("path"),
	depth: smallint().generatedAlwaysAs(sql`nlevel(path)`),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deactivatedBy: bigint("deactivated_by", { mode: "number" }),
	deactivatedAt: timestamp("deactivated_at", { withTimezone: true, mode: 'string' }),
	deactivationReason: text("deactivation_reason"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("users_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")),
	uniqueIndex("users_email_uk").using("btree", table.email.asc().nullsLast().op("citext_ops")).where(sql`(deleted_at IS NULL)`),
	index("users_locked_idx").using("btree", table.lockedUntil.asc().nullsLast().op("timestamptz_ops")).where(sql`(locked_until IS NOT NULL)`),
	index("users_login_idx").using("btree", table.email.asc().nullsLast().op("citext_ops"), table.passwordHash.asc().nullsLast().op("citext_ops"), table.status.asc().nullsLast().op("citext_ops"), table.lockedUntil.asc().nullsLast().op("citext_ops"), table.failedLoginCount.asc().nullsLast().op("citext_ops")).where(sql`(deleted_at IS NULL)`),
	uniqueIndex("users_mobile_uk").using("btree", table.mobile.asc().nullsLast().op("bpchar_ops")).where(sql`(deleted_at IS NULL)`),
	index("users_name_trgm").using("gin", sql`(((first_name || ' '::text) || last_name)) gin_trgm_ops`),
	index("users_path_gist").using("gist", table.path.asc().nullsLast().op("gist_ltree_ops")),
	index("users_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")).where(sql`(deleted_at IS NULL)`),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [table.id],
			name: "users_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deactivatedBy],
			foreignColumns: [table.id],
			name: "users_deactivated_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [table.id],
			name: "users_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [table.id],
			name: "users_updated_by_fkey"
		}),
	check("users_check", sql`(status <> 'SUSPENDED'::wms.record_status) OR (deactivation_reason IS NOT NULL)`),
]);

export const userSessionInWms = wms.table("user_session", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.user_session_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	tokenHash: text("token_hash").notNull(),
	activeRole: roleKeyInWms("active_role"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	activeWarehouseId: bigint("active_warehouse_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	activeImporterId: bigint("active_importer_id", { mode: "number" }),
	ip: inet(),
	userAgent: text("user_agent"),
	deviceName: text("device_name"),
	platform: text(),
	issuedAt: timestamp("issued_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }).notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
	revokedReason: text("revoked_reason"),
}, (table) => [
	index("user_session_cleanup_idx").using("btree", table.expiresAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(revoked_at IS NULL)`),
	index("user_session_expiry_idx").using("btree", table.expiresAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(revoked_at IS NULL)`),
	index("user_session_user_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "user_session_user_id_fkey"
		}).onDelete("cascade"),
	unique("user_session_token_hash_key").on(table.tokenHash),
	check("user_session_check", sql`expires_at > issued_at`),
	check("user_session_platform_check", sql`platform = ANY (ARRAY['WEB'::text, 'ANDROID'::text, 'IOS'::text])`),
]);

export const userVerificationTokenInWms = wms.table("user_verification_token", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.user_verification_token_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }),
	purpose: text().notNull(),
	tokenHash: text("token_hash").notNull(),
	sentTo: text("sent_to").notNull(),
	channel: text().notNull(),
	attempts: smallint().default(0).notNull(),
	maxAttempts: smallint("max_attempts").default(5).notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }).notNull(),
	consumedAt: timestamp("consumed_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	ip: inet(),
}, (table) => [
	uniqueIndex("user_token_hash_uk").using("btree", table.tokenHash.asc().nullsLast().op("text_ops")),
	index("user_token_lookup_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops"), table.purpose.asc().nullsLast().op("text_ops"), table.expiresAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(consumed_at IS NULL)`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "user_verification_token_user_id_fkey"
		}).onDelete("cascade"),
	check("user_verification_token_channel_check", sql`channel = ANY (ARRAY['EMAIL'::text, 'SMS'::text])`),
	check("user_verification_token_purpose_check", sql`purpose = ANY (ARRAY['EMAIL_VERIFY'::text, 'MOBILE_VERIFY'::text, 'PASSWORD_RESET'::text, 'LOGIN_OTP'::text, 'INVITE'::text])`),
]);

export const countryInWms = wms.table("country", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.country_id_seq", startWith: 1, increment: 1 }),
	iso2: char({ length: 2 }).notNull(),
	iso3: char({ length: 3 }).notNull(),
	name: text().notNull(),
	phoneCode: varchar("phone_code", { length: 6 }).notNull(),
	currencyCode: char("currency_code", { length: 3 }).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "country_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "country_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "country_updated_by_fkey"
		}),
	unique("country_iso2_key").on(table.iso2),
	unique("country_iso3_key").on(table.iso3),
]);

export const stateInWms = wms.table("state", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.state_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	countryId: bigint("country_id", { mode: "number" }).notNull(),
	code: text().notNull(),
	name: text().notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("state_country_idx").using("btree", table.countryId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.countryId],
			foreignColumns: [countryInWms.id],
			name: "state_country_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "state_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "state_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "state_updated_by_fkey"
		}),
	unique("state_country_id_code_key").on(table.countryId, table.code),
]);

export const cityInWms = wms.table("city", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.city_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	stateId: bigint("state_id", { mode: "number" }).notNull(),
	name: text().notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("city_state_idx").using("btree", table.stateId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "city_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "city_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.stateId],
			foreignColumns: [stateInWms.id],
			name: "city_state_id_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "city_updated_by_fkey"
		}),
	unique("city_state_id_name_key").on(table.stateId, table.name),
]);

export const vehicleTypeInWms = wms.table("vehicle_type", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.vehicle_type_id_seq", startWith: 1, increment: 1 }),
	code: text().notNull(),
	name: text().notNull(),
	category: text().notNull(),
	axleCount: smallint("axle_count"),
	capacityKg: numeric("capacity_kg", { precision: 10, scale:  2 }),
	capacityCbm: numeric("capacity_cbm", { precision: 10, scale:  2 }),
	lengthFt: numeric("length_ft", { precision: 6, scale:  2 }),
	widthFt: numeric("width_ft", { precision: 6, scale:  2 }),
	heightFt: numeric("height_ft", { precision: 6, scale:  2 }),
	isActive: boolean("is_active").default(true).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_type_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_type_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_type_updated_by_fkey"
		}),
	unique("vehicle_type_code_key").on(table.code),
	check("vehicle_type_category_check", sql`category = ANY (ARRAY['THREE_WHEELER'::text, 'LCV'::text, 'MCV'::text, 'HCV'::text, 'TRAILER'::text, 'CONTAINER'::text])`),
]);

export const warehouseTypeInWms = wms.table("warehouse_type", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.warehouse_type_id_seq", startWith: 1, increment: 1 }),
	code: text().notNull(),
	name: text().notNull(),
	description: text(),
	isActive: boolean("is_active").default(true).notNull(),
	sortOrder: smallint("sort_order").default(0).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_type_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_type_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_type_updated_by_fkey"
		}),
	unique("warehouse_type_code_key").on(table.code),
]);

export const warehouseInWms = wms.table("warehouse", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.warehouse_id_seq", startWith: 1, increment: 1 }),
	code: text().notNull(),
	name: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	warehouseTypeId: bigint("warehouse_type_id", { mode: "number" }).notNull(),
	address: text().notNull(),
	landmark: text(),
	area: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	cityId: bigint("city_id", { mode: "number" }).notNull(),
	pincode: pincodeIn("pincode").notNull(),
	latitude: numeric({ precision: 9, scale:  6 }),
	longitude: numeric({ precision: 9, scale:  6 }),
	gmapUrl: text("gmap_url"),
	totalAreaSqft: numeric("total_area_sqft", { precision: 12, scale:  2 }),
	usableAreaSqft: numeric("usable_area_sqft", { precision: 12, scale:  2 }),
	storageCapacityCbm: numeric("storage_capacity_cbm", { precision: 12, scale:  2 }),
	palletPositions: integer("pallet_positions"),
	dockCount: smallint("dock_count"),
	maxVehicleLengthFt: numeric("max_vehicle_length_ft", { precision: 6, scale:  2 }),
	floorCount: smallint("floor_count"),
	hasRacking: boolean("has_racking").default(true).notNull(),
	hasCctv: boolean("has_cctv").default(false).notNull(),
	hasWeighbridge: boolean("has_weighbridge").default(false).notNull(),
	contactPerson: text("contact_person"),
	contactMobile: mobileIn("contact_mobile"),
	alternateMobile: mobileIn("alternate_mobile"),
	isActive: boolean("is_active").default(true).notNull(),
	notes: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("warehouse_active_idx").using("btree", table.isActive.asc().nullsLast().op("bool_ops")).where(sql`(deleted_at IS NULL)`),
	index("warehouse_city_fk_idx").using("btree", table.cityId.asc().nullsLast().op("int8_ops")),
	index("warehouse_city_idx").using("btree", table.cityId.asc().nullsLast().op("int8_ops")).where(sql`(deleted_at IS NULL)`),
	index("warehouse_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")),
	index("warehouse_name_trgm").using("gin", table.name.asc().nullsLast().op("gin_trgm_ops")),
	index("warehouse_type_fk_idx").using("btree", table.warehouseTypeId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.cityId],
			foreignColumns: [cityInWms.id],
			name: "warehouse_city_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_updated_by_fkey"
		}),
	foreignKey({
			columns: [table.warehouseTypeId],
			foreignColumns: [warehouseTypeInWms.id],
			name: "warehouse_warehouse_type_id_fkey"
		}),
	unique("warehouse_code_key").on(table.code),
	check("warehouse_check", sql`(usable_area_sqft IS NULL) OR (total_area_sqft IS NULL) OR (usable_area_sqft <= total_area_sqft)`),
]);

export const importerInWms = wms.table("importer", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.importer_id_seq", startWith: 1, increment: 1 }),
	code: text().notNull(),
	companyName: text("company_name").notNull(),
	legalName: text("legal_name").notNull(),
	tradeName: text("trade_name"),
	entityType: text("entity_type").notNull(),
	address: text().notNull(),
	landmark: text(),
	area: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	cityId: bigint("city_id", { mode: "number" }).notNull(),
	pincode: pincodeIn("pincode").notNull(),
	gstin: gstin("gstin"),
	pan: panNo("pan"),
	contactPerson: text("contact_person").notNull(),
	contactEmail: citext("contact_email").notNull(),
	contactMobile: mobileIn("contact_mobile").notNull(),
	alternateMobile: mobileIn("alternate_mobile"),
	creditLimit: numeric("credit_limit", { precision: 14, scale:  2 }).default('0').notNull(),
	creditDays: smallint("credit_days").default(0).notNull(),
	paymentTerms: text("payment_terms"),
	currencyCode: char("currency_code", { length: 3 }).default('INR').notNull(),
	billingCycle: text("billing_cycle").default('MONTHLY').notNull(),
	isCreditBlocked: boolean("is_credit_blocked").default(false).notNull(),
	creditBlockReason: text("credit_block_reason"),
	origin: text().notNull(),
	status: recordStatusInWms().default('PENDING').notNull(),
	kycStatus: text("kyc_status").default('NOT_STARTED').notNull(),
	kycSubmittedAt: timestamp("kyc_submitted_at", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	approvedBy: bigint("approved_by", { mode: "number" }),
	approvedAt: timestamp("approved_at", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	rejectedBy: bigint("rejected_by", { mode: "number" }),
	rejectedAt: timestamp("rejected_at", { withTimezone: true, mode: 'string' }),
	rejectionReason: text("rejection_reason"),
	suspendedReason: text("suspended_reason"),
	notes: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("importer_approved_by_idx").using("btree", table.approvedBy.asc().nullsLast().op("int8_ops")).where(sql`(approved_by IS NOT NULL)`),
	index("importer_city_fk_idx").using("btree", table.cityId.asc().nullsLast().op("int8_ops")),
	index("importer_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")).where(sql`(created_by IS NOT NULL)`),
	uniqueIndex("importer_gstin_uk").using("btree", table.gstin.asc().nullsLast().op("bpchar_ops")).where(sql`((gstin IS NOT NULL) AND (deleted_at IS NULL))`),
	index("importer_kyc_idx").using("btree", table.kycStatus.asc().nullsLast().op("text_ops")).where(sql`(deleted_at IS NULL)`),
	index("importer_kyc_queue_idx").using("btree", table.kycStatus.asc().nullsLast().op("text_ops"), table.createdAt.asc().nullsLast().op("timestamptz_ops")).where(sql`((deleted_at IS NULL) AND (kyc_status = ANY (ARRAY['SUBMITTED'::text, 'UNDER_REVIEW'::text])))`),
	index("importer_name_trgm").using("gin", table.companyName.asc().nullsLast().op("gin_trgm_ops")),
	uniqueIndex("importer_pan_uk").using("btree", table.pan.asc().nullsLast().op("bpchar_ops")).where(sql`((pan IS NOT NULL) AND (deleted_at IS NULL))`),
	index("importer_pending_idx").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")).where(sql`((deleted_at IS NULL) AND (status = 'PENDING'::wms.record_status))`),
	index("importer_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")).where(sql`(deleted_at IS NULL)`),
	foreignKey({
			columns: [table.approvedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_approved_by_fkey"
		}),
	foreignKey({
			columns: [table.cityId],
			foreignColumns: [cityInWms.id],
			name: "importer_city_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "importer_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.rejectedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_rejected_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_updated_by_fkey"
		}),
	unique("importer_code_key").on(table.code),
	check("importer_billing_cycle_check", sql`billing_cycle = ANY (ARRAY['WEEKLY'::text, 'FORTNIGHTLY'::text, 'MONTHLY'::text, 'PER_TRANSACTION'::text])`),
	check("importer_check", sql`((origin = 'SELF_REGISTERED'::text) AND (created_by IS NULL)) OR ((origin = 'CREATED_BY_ADMIN'::text) AND (created_by IS NOT NULL))`),
	check("importer_check1", sql`(status <> 'REJECTED'::wms.record_status) OR (rejection_reason IS NOT NULL)`),
	check("importer_check2", sql`(NOT is_credit_blocked) OR (credit_block_reason IS NOT NULL)`),
	check("importer_entity_type_check", sql`entity_type = ANY (ARRAY['PROPRIETORSHIP'::text, 'PARTNERSHIP'::text, 'LLP'::text, 'PRIVATE_LIMITED'::text, 'PUBLIC_LIMITED'::text, 'HUF'::text, 'TRUST'::text, 'SOCIETY'::text, 'GOVERNMENT'::text])`),
	check("importer_kyc_status_check", sql`kyc_status = ANY (ARRAY['NOT_STARTED'::text, 'SUBMITTED'::text, 'UNDER_REVIEW'::text, 'VERIFIED'::text, 'REJECTED'::text])`),
	check("importer_origin_check", sql`origin = ANY (ARRAY['SELF_REGISTERED'::text, 'CREATED_BY_ADMIN'::text])`),
]);

export const importerClientInWms = wms.table("importer_client", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.importer_client_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	importerId: bigint("importer_id", { mode: "number" }).notNull(),
	code: text(),
	name: text().notNull(),
	legalName: text("legal_name"),
	gstin: gstin("gstin"),
	contactPerson: text("contact_person"),
	contactMobile: mobileIn("contact_mobile").notNull(),
	contactEmail: citext("contact_email"),
	address: text(),
	landmark: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	cityId: bigint("city_id", { mode: "number" }),
	pincode: pincodeIn("pincode"),
	status: recordStatusInWms().default('ACTIVE').notNull(),
	notes: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("importer_client_city_idx").using("btree", table.cityId.asc().nullsLast().op("int8_ops")),
	index("importer_client_idx").using("btree", table.importerId.asc().nullsLast().op("int8_ops")).where(sql`(deleted_at IS NULL)`),
	index("importer_client_name_trgm").using("gin", table.name.asc().nullsLast().op("gin_trgm_ops")),
	foreignKey({
			columns: [table.cityId],
			foreignColumns: [cityInWms.id],
			name: "importer_client_city_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "importer_client_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_client_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.importerId],
			foreignColumns: [importerInWms.id],
			name: "importer_client_importer_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "importer_client_updated_by_fkey"
		}),
	unique("importer_client_importer_id_code_key").on(table.importerId, table.code),
]);

export const salesAgentClientInWms = wms.table("sales_agent_client", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.sales_agent_client_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	agentUserId: bigint("agent_user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	clientId: bigint("client_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	assignedBy: bigint("assigned_by", { mode: "number" }).notNull(),
	assignedAt: timestamp("assigned_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	revokedBy: bigint("revoked_by", { mode: "number" }),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("agent_client_client_idx").using("btree", table.clientId.asc().nullsLast().op("int8_ops")),
	uniqueIndex("sales_agent_client_uk").using("btree", table.agentUserId.asc().nullsLast().op("int8_ops"), table.clientId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	foreignKey({
			columns: [table.agentUserId],
			foreignColumns: [usersInWms.id],
			name: "sales_agent_client_agent_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.assignedBy],
			foreignColumns: [usersInWms.id],
			name: "sales_agent_client_assigned_by_fkey"
		}),
	foreignKey({
			columns: [table.clientId],
			foreignColumns: [importerClientInWms.id],
			name: "sales_agent_client_client_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.revokedBy],
			foreignColumns: [usersInWms.id],
			name: "sales_agent_client_revoked_by_fkey"
		}),
]);

export const transporterInWms = wms.table("transporter", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.transporter_id_seq", startWith: 1, increment: 1 }),
	code: text().notNull(),
	name: text().notNull(),
	legalName: text("legal_name"),
	gstin: gstin("gstin"),
	pan: panNo("pan"),
	contactPerson: text("contact_person").notNull(),
	contactMobile: mobileIn("contact_mobile").notNull(),
	alternateMobile: mobileIn("alternate_mobile"),
	contactEmail: citext("contact_email"),
	officePhone: varchar("office_phone", { length: 15 }),
	website: text(),
	address: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	cityId: bigint("city_id", { mode: "number" }),
	pincode: pincodeIn("pincode"),
	status: recordStatusInWms().default('ACTIVE').notNull(),
	blacklisted: boolean().default(false).notNull(),
	blacklistReason: text("blacklist_reason"),
	notes: text(),
	metadata: jsonb().default({}).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("transporter_city_fk_idx").using("btree", table.cityId.asc().nullsLast().op("int8_ops")),
	index("transporter_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")),
	uniqueIndex("transporter_gstin_uk").using("btree", table.gstin.asc().nullsLast().op("bpchar_ops")).where(sql`((gstin IS NOT NULL) AND (deleted_at IS NULL))`),
	index("transporter_name_trgm").using("gin", table.name.asc().nullsLast().op("gin_trgm_ops")),
	index("transporter_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")).where(sql`(deleted_at IS NULL)`),
	foreignKey({
			columns: [table.cityId],
			foreignColumns: [cityInWms.id],
			name: "transporter_city_id_fkey"
		}),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "transporter_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "transporter_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "transporter_updated_by_fkey"
		}),
	unique("transporter_code_key").on(table.code),
	check("transporter_check", sql`(NOT blacklisted) OR (blacklist_reason IS NOT NULL)`),
]);

export const vehicleInWms = wms.table("vehicle", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.vehicle_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transporterId: bigint("transporter_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	vehicleTypeId: bigint("vehicle_type_id", { mode: "number" }).notNull(),
	registrationNumber: vehicleReg("registration_number").notNull(),
	chassisNumber: varchar("chassis_number", { length: 25 }),
	engineNumber: varchar("engine_number", { length: 25 }),
	model: text(),
	fuelType: text("fuel_type"),
	capacityKg: numeric("capacity_kg", { precision: 10, scale:  2 }),
	capacityCbm: numeric("capacity_cbm", { precision: 10, scale:  2 }),
	lengthFt: numeric("length_ft", { precision: 6, scale:  2 }),
	widthFt: numeric("width_ft", { precision: 6, scale:  2 }),
	heightFt: numeric("height_ft", { precision: 6, scale:  2 }),
	axleCount: smallint("axle_count"),
	status: recordStatusInWms().default('ACTIVE').notNull(),
	notes: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	deletedBy: bigint("deleted_by", { mode: "number" }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("vehicle_active_idx").using("btree", table.transporterId.asc().nullsLast().op("int8_ops")).where(sql`((deleted_at IS NULL) AND (status = 'ACTIVE'::wms.record_status))`),
	index("vehicle_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")),
	index("vehicle_reg_trgm").using("gin", table.registrationNumber.asc().nullsLast().op("gin_trgm_ops")),
	uniqueIndex("vehicle_registration_uk").using("btree", table.registrationNumber.asc().nullsLast().op("text_ops")).where(sql`(deleted_at IS NULL)`),
	index("vehicle_transporter_idx").using("btree", table.transporterId.asc().nullsLast().op("int8_ops")).where(sql`(deleted_at IS NULL)`),
	index("vehicle_type_fk_idx").using("btree", table.vehicleTypeId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_created_by_fkey"
		}),
	foreignKey({
			columns: [table.deletedBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_deleted_by_fkey"
		}),
	foreignKey({
			columns: [table.transporterId],
			foreignColumns: [transporterInWms.id],
			name: "vehicle_transporter_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "vehicle_updated_by_fkey"
		}),
	foreignKey({
			columns: [table.vehicleTypeId],
			foreignColumns: [vehicleTypeInWms.id],
			name: "vehicle_vehicle_type_id_fkey"
		}),
	check("vehicle_fuel_type_check", sql`fuel_type = ANY (ARRAY['DIESEL'::text, 'PETROL'::text, 'CNG'::text, 'LNG'::text, 'ELECTRIC'::text, 'HYBRID'::text])`),
]);

export const roleInWms = wms.table("role", {
	key: roleKeyInWms().primaryKey().notNull(),
	domain: roleDomainInWms().notNull(),
	name: text().notNull(),
	level: smallint().notNull(),
	isProtected: boolean("is_protected").default(false).notNull(),
	isExclusive: boolean("is_exclusive").default(false).notNull(),
	isImmutable: boolean("is_immutable").default(false).notNull(),
	description: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const permissionInWms = wms.table("permission", {
	key: text().primaryKey().notNull(),
	resource: text().notNull(),
	action: text().notNull(),
	module: text().notNull(),
	isDangerous: boolean("is_dangerous").default(false).notNull(),
	description: text().notNull(),
}, (table) => [
	index("permission_resource_idx").using("btree", table.resource.asc().nullsLast().op("text_ops")),
	check("permission_action_check", sql`action = ANY (ARRAY['create'::text, 'read'::text, 'update'::text, 'delete'::text, 'approve'::text, 'export'::text, 'assign'::text])`),
]);

export const roleCreationRuleInWms = wms.table("role_creation_rule", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.role_creation_rule_id_seq", startWith: 1, increment: 1 }),
	actorRole: roleKeyInWms("actor_role"),
	targetRole: roleKeyInWms("target_role").notNull(),
	scope: creationScopeInWms().notNull(),
	note: text(),
}, (table) => [
	index("creation_rule_target_idx").using("btree", table.targetRole.asc().nullsLast().op("enum_ops")),
	uniqueIndex("role_creation_rule_uk").using("btree", table.actorRole.asc().nullsLast().op("enum_ops"), table.targetRole.asc().nullsLast().op("enum_ops")),
	foreignKey({
			columns: [table.actorRole],
			foreignColumns: [roleInWms.key],
			name: "role_creation_rule_actor_role_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.targetRole],
			foreignColumns: [roleInWms.key],
			name: "role_creation_rule_target_role_fkey"
		}).onDelete("cascade"),
]);

export const userRoleAssignmentInWms = wms.table("user_role_assignment", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.user_role_assignment_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	role: roleKeyInWms().notNull(),
	roleDomain: roleDomainInWms("role_domain").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	warehouseId: bigint("warehouse_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	importerId: bigint("importer_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	assignedBy: bigint("assigned_by", { mode: "number" }),
	assignedAt: timestamp("assigned_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	revokedBy: bigint("revoked_by", { mode: "number" }),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
	revokeReason: text("revoke_reason"),
	note: text(),
}, (table) => [
	index("ura_assigned_by_idx").using("btree", table.assignedBy.asc().nullsLast().op("int8_ops")).where(sql`(assigned_by IS NOT NULL)`),
	index("ura_importer_idx").using("btree", table.importerId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	index("ura_role_idx").using("btree", table.role.asc().nullsLast().op("enum_ops")).where(sql`(revoked_at IS NULL)`),
	index("ura_role_importer_idx").using("btree", table.role.asc().nullsLast().op("enum_ops"), table.importerId.asc().nullsLast().op("int8_ops")).where(sql`((revoked_at IS NULL) AND (importer_id IS NOT NULL))`),
	index("ura_role_warehouse_idx").using("btree", table.role.asc().nullsLast().op("enum_ops"), table.warehouseId.asc().nullsLast().op("int8_ops")).where(sql`((revoked_at IS NULL) AND (warehouse_id IS NOT NULL))`),
	index("ura_user_active_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops"), table.role.asc().nullsLast().op("int8_ops"), table.roleDomain.asc().nullsLast().op("int8_ops"), table.warehouseId.asc().nullsLast().op("int8_ops"), table.importerId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	index("ura_user_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	index("ura_warehouse_idx").using("btree", table.warehouseId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	uniqueIndex("user_role_assignment_uk").using("btree", table.userId.asc().nullsLast().op("int8_ops"), table.role.asc().nullsLast().op("enum_ops"), table.warehouseId.asc().nullsLast().op("int8_ops"), table.importerId.asc().nullsLast().op("int8_ops")).where(sql`(revoked_at IS NULL)`),
	foreignKey({
			columns: [table.assignedBy],
			foreignColumns: [usersInWms.id],
			name: "user_role_assignment_assigned_by_fkey"
		}),
	foreignKey({
			columns: [table.importerId],
			foreignColumns: [importerInWms.id],
			name: "user_role_assignment_importer_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.revokedBy],
			foreignColumns: [usersInWms.id],
			name: "user_role_assignment_revoked_by_fkey"
		}),
	foreignKey({
			columns: [table.role, table.roleDomain],
			foreignColumns: [roleInWms.key, roleInWms.domain],
			name: "user_role_assignment_role_role_domain_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "user_role_assignment_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.warehouseId],
			foreignColumns: [warehouseInWms.id],
			name: "user_role_assignment_warehouse_id_fkey"
		}).onDelete("cascade"),
	check("user_role_assignment_check", sql`CHECK (
CASE role_domain
    WHEN 'PLATFORM'::wms.role_domain THEN ((warehouse_id IS NULL) AND (importer_id IS NULL))
    WHEN 'WAREHOUSE'::wms.role_domain THEN ((warehouse_id IS NOT NULL) AND (importer_id IS NULL))
    WHEN 'IMPORTER'::wms.role_domain THEN ((importer_id IS NOT NULL) AND (warehouse_id IS NULL))
    ELSE NULL::boolean
END)`),
	check("user_role_assignment_check1", sql`(revoked_at IS NULL) OR (revoke_reason IS NOT NULL)`),
]);

export const permissionOverrideInWms = wms.table("permission_override", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.permission_override_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	permission: text().notNull(),
	effect: text().default('DENY').notNull(),
	reason: text().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	grantedBy: bigint("granted_by", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("perm_override_perm_idx").using("btree", table.permission.asc().nullsLast().op("text_ops")),
	uniqueIndex("permission_override_uk").using("btree", table.userId.asc().nullsLast().op("int8_ops"), table.permission.asc().nullsLast().op("text_ops")).where(sql`(revoked_at IS NULL)`),
	foreignKey({
			columns: [table.grantedBy],
			foreignColumns: [usersInWms.id],
			name: "permission_override_granted_by_fkey"
		}),
	foreignKey({
			columns: [table.permission],
			foreignColumns: [permissionInWms.key],
			name: "permission_override_permission_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "permission_override_user_id_fkey"
		}).onDelete("cascade"),
	check("permission_override_effect_check", sql`effect = 'DENY'::text`),
]);

export const notificationEventInWms = wms.table("notification_event", {
	key: text().primaryKey().notNull(),
	module: text().notNull(),
	name: text().notNull(),
	description: text(),
	payloadSchema: jsonb("payload_schema").default({}).notNull(),
	defaultPriority: smallint("default_priority").default(5).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
});

export const notificationTemplateInWms = wms.table("notification_template", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.notification_template_id_seq", startWith: 1, increment: 1 }),
	eventKey: text("event_key").notNull(),
	channel: notifChannelInWms().notNull(),
	locale: text().default('en').notNull(),
	version: smallint().default(1).notNull(),
	subject: text(),
	body: text().notNull(),
	actionUrl: text("action_url"),
	dltTemplateId: text("dlt_template_id"),
	dltEntityId: text("dlt_entity_id"),
	senderId: varchar("sender_id", { length: 11 }),
	isActive: boolean("is_active").default(true).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	updatedBy: bigint("updated_by", { mode: "number" }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [usersInWms.id],
			name: "notification_template_created_by_fkey"
		}),
	foreignKey({
			columns: [table.eventKey],
			foreignColumns: [notificationEventInWms.key],
			name: "notification_template_event_key_fkey"
		}),
	foreignKey({
			columns: [table.updatedBy],
			foreignColumns: [usersInWms.id],
			name: "notification_template_updated_by_fkey"
		}),
	unique("notification_template_event_key_channel_locale_version_key").on(table.eventKey, table.channel, table.locale, table.version),
	check("notification_template_check", sql`(channel <> 'SMS'::wms.notif_channel) OR (dlt_template_id IS NOT NULL)`),
	check("notification_template_check1", sql`(channel <> 'EMAIL'::wms.notif_channel) OR (subject IS NOT NULL)`),
]);

export const notificationInWms = wms.table("notification", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.notification_id_seq", startWith: 1, increment: 1 }),
	eventKey: text("event_key").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	ruleId: bigint("rule_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	recipientUserId: bigint("recipient_user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	actorUserId: bigint("actor_user_id", { mode: "number" }),
	entityType: text("entity_type"),
	entityId: text("entity_id"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	warehouseId: bigint("warehouse_id", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	importerId: bigint("importer_id", { mode: "number" }),
	title: text().notNull(),
	body: text().notNull(),
	actionUrl: text("action_url"),
	payload: jsonb().default({}).notNull(),
	priority: smallint().default(5).notNull(),
	correlationId: text("correlation_id"),
	dedupeKey: text("dedupe_key").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	readAt: timestamp("read_at", { withTimezone: true, mode: 'string' }),
	archivedAt: timestamp("archived_at", { withTimezone: true, mode: 'string' }),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("notification_actor_idx").using("btree", table.actorUserId.asc().nullsLast().op("int8_ops")).where(sql`(actor_user_id IS NOT NULL)`),
	index("notification_correlation_idx").using("btree", table.correlationId.asc().nullsLast().op("text_ops")).where(sql`(correlation_id IS NOT NULL)`),
	uniqueIndex("notification_dedupe_uk").using("btree", table.dedupeKey.asc().nullsLast().op("text_ops")),
	index("notification_entity_idx").using("btree", table.entityType.asc().nullsLast().op("text_ops"), table.entityId.asc().nullsLast().op("text_ops")),
	index("notification_event_fk_idx").using("btree", table.eventKey.asc().nullsLast().op("text_ops")),
	index("notification_feed_idx").using("btree", table.recipientUserId.asc().nullsLast().op("int8_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("notification_imp_idx").using("btree", table.importerId.asc().nullsLast().op("int8_ops")).where(sql`(importer_id IS NOT NULL)`),
	index("notification_rule_fk_idx").using("btree", table.ruleId.asc().nullsLast().op("int8_ops")),
	index("notification_unread_idx").using("btree", table.recipientUserId.asc().nullsLast().op("int8_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")).where(sql`(read_at IS NULL)`),
	index("notification_wh_idx").using("btree", table.warehouseId.asc().nullsLast().op("int8_ops")).where(sql`(warehouse_id IS NOT NULL)`),
	foreignKey({
			columns: [table.actorUserId],
			foreignColumns: [usersInWms.id],
			name: "notification_actor_user_id_fkey"
		}),
	foreignKey({
			columns: [table.eventKey],
			foreignColumns: [notificationEventInWms.key],
			name: "notification_event_key_fkey"
		}),
	foreignKey({
			columns: [table.importerId],
			foreignColumns: [importerInWms.id],
			name: "notification_importer_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.recipientUserId],
			foreignColumns: [usersInWms.id],
			name: "notification_recipient_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.ruleId],
			foreignColumns: [notificationRuleInWms.id],
			name: "notification_rule_id_fkey"
		}),
	foreignKey({
			columns: [table.warehouseId],
			foreignColumns: [warehouseInWms.id],
			name: "notification_warehouse_id_fkey"
		}).onDelete("set null"),
	check("notification_priority_check", sql`(priority >= 1) AND (priority <= 9)`),
]);

export const notificationRuleInWms = wms.table("notification_rule", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.notification_rule_id_seq", startWith: 1, increment: 1 }),
	eventKey: text("event_key").notNull(),
	audience: notifAudienceInWms().notNull(),
	roleFilter: roleKeyInWms("role_filter"),
	channels: notifChannelArray("channels").default(["IN_APP"]).notNull(),
	isMandatory: boolean("is_mandatory").default(false).notNull(),
	condition: jsonb(),
	delayMinutes: integer("delay_minutes").default(0).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("notif_rule_role_idx").using("btree", table.roleFilter.asc().nullsLast().op("enum_ops")).where(sql`(role_filter IS NOT NULL)`),
	index("notification_rule_event_idx").using("btree", table.eventKey.asc().nullsLast().op("text_ops")).where(sql`is_active`),
	uniqueIndex("notification_rule_uk").using("btree", table.eventKey.asc().nullsLast().op("text_ops"), table.audience.asc().nullsLast().op("enum_ops"), table.roleFilter.asc().nullsLast().op("enum_ops")),
	foreignKey({
			columns: [table.eventKey],
			foreignColumns: [notificationEventInWms.key],
			name: "notification_rule_event_key_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.roleFilter],
			foreignColumns: [roleInWms.key],
			name: "notification_rule_role_filter_fkey"
		}),
	check("notification_rule_channels_check", sql`array_length(channels, 1) > 0`),
	check("notification_rule_check", sql`(audience <> ALL (ARRAY['ROLE'::wms.notif_audience, 'WAREHOUSE_ROLE'::wms.notif_audience, 'IMPORTER_ROLE'::wms.notif_audience])) OR (role_filter IS NOT NULL)`),
]);

export const notificationQuietHoursInWms = wms.table("notification_quiet_hours", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).primaryKey().notNull(),
	startTime: time("start_time").default('22:00:00').notNull(),
	endTime: time("end_time").default('07:00:00').notNull(),
	timezone: text().default('Asia/Kolkata').notNull(),
	appliesTo: notifChannelArray("applies_to").default(["SMS", "PUSH"]).notNull(),
	isEnabled: boolean("is_enabled").default(true).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "notification_quiet_hours_user_id_fkey"
		}).onDelete("cascade"),
]);

export const notificationDeliveryInWms = wms.table("notification_delivery", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.notification_delivery_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	notificationId: bigint("notification_id", { mode: "number" }).notNull(),
	channel: notifChannelInWms().notNull(),
	address: text().notNull(),
	status: deliveryStatusInWms().default('PENDING').notNull(),
	provider: text(),
	providerMessageId: text("provider_message_id"),
	providerResponse: jsonb("provider_response"),
	attempts: smallint().default(0).notNull(),
	maxAttempts: smallint("max_attempts").default(3).notNull(),
	lastError: text("last_error"),
	errorCode: text("error_code"),
	scheduledFor: timestamp("scheduled_for", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	nextRetryAt: timestamp("next_retry_at", { withTimezone: true, mode: 'string' }),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'string' }),
	deliveredAt: timestamp("delivered_at", { withTimezone: true, mode: 'string' }),
	failedAt: timestamp("failed_at", { withTimezone: true, mode: 'string' }),
	costPaise: integer("cost_paise"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("notif_delivery_due_idx").using("btree", table.scheduledFor.asc().nullsLast().op("timestamptz_ops")).where(sql`(status = ANY (ARRAY['PENDING'::wms.delivery_status, 'QUEUED'::wms.delivery_status]))`),
	index("notif_delivery_notification_idx").using("btree", table.notificationId.asc().nullsLast().op("int8_ops")),
	uniqueIndex("notif_delivery_provider_uk").using("btree", table.provider.asc().nullsLast().op("text_ops"), table.providerMessageId.asc().nullsLast().op("text_ops")).where(sql`(provider_message_id IS NOT NULL)`),
	index("notif_delivery_retry_idx").using("btree", table.nextRetryAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(status = 'FAILED'::wms.delivery_status)`),
	index("notif_delivery_worker_idx").using("btree", table.scheduledFor.asc().nullsLast().op("timestamptz_ops"), table.channel.asc().nullsLast().op("enum_ops")).where(sql`(status = ANY (ARRAY['PENDING'::wms.delivery_status, 'QUEUED'::wms.delivery_status]))`),
	foreignKey({
			columns: [table.notificationId],
			foreignColumns: [notificationInWms.id],
			name: "notification_delivery_notification_id_fkey"
		}).onDelete("cascade"),
]);

export const userDeviceInWms = wms.table("user_device", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "wms.user_device_id_seq", startWith: 1, increment: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	platform: text().notNull(),
	pushToken: text("push_token").notNull(),
	deviceModel: text("device_model"),
	osVersion: text("os_version"),
	appVersion: text("app_version"),
	lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("user_device_token_uk").using("btree", table.pushToken.asc().nullsLast().op("text_ops")),
	index("user_device_user_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")).where(sql`is_active`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "user_device_user_id_fkey"
		}).onDelete("cascade"),
	check("user_device_platform_check", sql`platform = ANY (ARRAY['ANDROID'::text, 'IOS'::text, 'WEB'::text])`),
]);

export const rolePermissionInWms = wms.table("role_permission", {
	role: roleKeyInWms().notNull(),
	permission: text().notNull(),
	scope: accessScopeInWms().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("role_permission_perm_idx").using("btree", table.permission.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.permission],
			foreignColumns: [permissionInWms.key],
			name: "role_permission_permission_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.role],
			foreignColumns: [roleInWms.key],
			name: "role_permission_role_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.role, table.permission], name: "role_permission_pkey"}),
	check("role_permission_scope_check", sql`scope <> 'NONE'::wms.access_scope`),
]);

export const notificationPreferenceInWms = wms.table("notification_preference", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	eventKey: text("event_key").notNull(),
	channel: notifChannelInWms().notNull(),
	enabled: boolean().default(true).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("notif_pref_event_idx").using("btree", table.eventKey.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.eventKey],
			foreignColumns: [notificationEventInWms.key],
			name: "notification_preference_event_key_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [usersInWms.id],
			name: "notification_preference_user_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.userId, table.eventKey, table.channel], name: "notification_preference_pkey"}),
]);

export const warehouseTransporterInWms = wms.table("warehouse_transporter", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	warehouseId: bigint("warehouse_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	transporterId: bigint("transporter_id", { mode: "number" }).notNull(),
	isPreferred: boolean("is_preferred").default(false).notNull(),
	contractRef: text("contract_ref"),
	contractStart: date("contract_start"),
	contractEnd: date("contract_end"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	approvedBy: bigint("approved_by", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("wh_transporter_trp_idx").using("btree", table.transporterId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.approvedBy],
			foreignColumns: [usersInWms.id],
			name: "warehouse_transporter_approved_by_fkey"
		}),
	foreignKey({
			columns: [table.transporterId],
			foreignColumns: [transporterInWms.id],
			name: "warehouse_transporter_transporter_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.warehouseId],
			foreignColumns: [warehouseInWms.id],
			name: "warehouse_transporter_warehouse_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.warehouseId, table.transporterId], name: "warehouse_transporter_pkey"}),
]);
export const userEffectivePermissionInWms = wms.view("user_effective_permission", {	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }),
	permission: text(),
	scopeRank: smallint("scope_rank"),
	scope: accessScopeInWms(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	warehouseIds: bigint("warehouse_ids", { mode: "number" }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	importerIds: bigint("importer_ids", { mode: "number" }),
	grantedByRoles: roleKeyArray("granted_by_roles"),
}).as(sql`SELECT ura.user_id, rp.permission, max(wms.access_rank(rp.scope)) AS scope_rank, (array_agg(rp.scope ORDER BY (wms.access_rank(rp.scope)) DESC))[1] AS scope, array_remove(array_agg(DISTINCT ura.warehouse_id), NULL::bigint) AS warehouse_ids, array_remove(array_agg(DISTINCT ura.importer_id), NULL::bigint) AS importer_ids, array_agg(DISTINCT ura.role) AS granted_by_roles FROM wms.user_role_assignment ura JOIN wms.role_permission rp ON rp.role = ura.role JOIN wms.users au ON au.id = ura.user_id WHERE ura.revoked_at IS NULL AND au.deleted_at IS NULL AND au.status = 'ACTIVE'::wms.record_status AND NOT (EXISTS ( SELECT 1 FROM wms.permission_override po WHERE po.user_id = ura.user_id AND po.permission = rp.permission AND po.revoked_at IS NULL AND (po.expires_at IS NULL OR po.expires_at > now()))) GROUP BY ura.user_id, rp.permission`);

export const vLastChangeInWms = wms.view("v_last_change", {	entityType: text("entity_type"),
	entityId: text("entity_id"),
	entityLabel: text("entity_label"),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	actorUserId: bigint("actor_user_id", { mode: "number" }),
	actorName: text("actor_name"),
	actingRole: roleKeyInWms("acting_role"),
	operation: auditOperationInWms(),
	diff: jsonb(),
	reason: text(),
}).as(sql`SELECT DISTINCT ON (entity_type, entity_id) entity_type, entity_id, entity_label, occurred_at, actor_user_id, actor_name, acting_role, operation, diff, reason FROM wms.audit_log WHERE result = 'SUCCESS'::wms.audit_result AND (operation = ANY (ARRAY['INSERT'::wms.audit_operation, 'UPDATE'::wms.audit_operation, 'DELETE'::wms.audit_operation, 'RESTORE'::wms.audit_operation])) ORDER BY entity_type, entity_id, occurred_at DESC`);